//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StringUtilities.ConsoleClient.StringServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StringServiceReference.IStringService")]
    public interface IStringService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringService/GetOccurrences", ReplyAction="http://tempuri.org/IStringService/GetOccurrencesResponse")]
        int GetOccurrences(string template, string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStringService/GetOccurrences", ReplyAction="http://tempuri.org/IStringService/GetOccurrencesResponse")]
        System.Threading.Tasks.Task<int> GetOccurrencesAsync(string template, string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStringServiceChannel : StringUtilities.ConsoleClient.StringServiceReference.IStringService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StringServiceClient : System.ServiceModel.ClientBase<StringUtilities.ConsoleClient.StringServiceReference.IStringService>, StringUtilities.ConsoleClient.StringServiceReference.IStringService {
        
        public StringServiceClient() {
        }
        
        public StringServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StringServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StringServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetOccurrences(string template, string text) {
            return base.Channel.GetOccurrences(template, text);
        }
        
        public System.Threading.Tasks.Task<int> GetOccurrencesAsync(string template, string text) {
            return base.Channel.GetOccurrencesAsync(template, text);
        }
    }
}
